Add missing import.
device/google/contexthub/contexthubhal/NanohubHidlAdapter.cpp:527:25: error: use of undeclared identifier 'O_RDONLY'
    int fd = open(file, O_RDONLY);
                        ^
device/google/contexthub/contexthubhal/system_comms.cpp:1114:25: error: use of undeclared identifier 'O_CREAT'
    int fd = open(file, O_CREAT | O_WRONLY | O_TRUNC, CHRE_APP_FILE_PERMS);
                        ^
device/google/contexthub/contexthubhal/system_comms.cpp:1114:35: error: use of undeclared identifier 'O_WRONLY'
    int fd = open(file, O_CREAT | O_WRONLY | O_TRUNC, CHRE_APP_FILE_PERMS);
                                  ^
device/google/contexthub/contexthubhal/system_comms.cpp:1114:46: error: use of undeclared identifier 'O_TRUNC'
    int fd = open(file, O_CREAT | O_WRONLY | O_TRUNC, CHRE_APP_FILE_PERMS);
                                             ^
device/google/contexthub/contexthubhal/system_comms.cpp:1135:25: error: use of undeclared identifier 'O_RDONLY'
    int fd = open(file, O_RDONLY);
                        ^
device/google/contexthub/contexthubhal/system_comms.cpp:1167:25: error: use of undeclared identifier 'O_RDONLY'
    int fd = open(file, O_RDONLY);
                        ^

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I3f8c00d8ea6415023771ef5091e4053feb3fac69